version: '3'

services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - '8080:80' # Внешний порт 8080, внутренний порт 80
        networks:
            - web
        environment:
            - NODE_ENV=production

    nginx:
        image: nginx:latest
        restart: always
        ports:
            - '80:80' # HTTP
            - '443:443' # HTTPS
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./certbot/conf:/etc/letsencrypt # SSL сертификаты
            - ./certbot/www:/var/www/certbot # Certbot будет сохранять свои файлы для проверки здесь
        depends_on:
            - frontend
        networks:
            - web

    certbot:
        image: certbot/certbot
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $!; done;'"
        networks:
            - web

networks:
    web:
        external: true # Используем общую сеть, если она уже создана
